title: Richard Fridström # your name (or website title) here
logo: "jagKTH.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  > Physics (PhD in Fusion Plasma Physics) 
  <br><br>
  > Mathematical modelling and signal analysis (MATLAB) 
  <br><br>
  > Programming  (Python, C#, Java)
  <br><br>
  > Monte Carlo Nuclear Criticality simulations (MCNP)
  <br><br>
  <a href="http://www.diva-portal.org/smash/record.jsf?dswid=863&pid=diva2%3A1159102&c=8&searchType=SIMPLE&language=sv&query=richard+fridstr%C3%B6m&af=%5B%5D&aq=%5B%5B%5D%5D&aq2=%5B%5B%5D%5D&aqe=%5B%5D&noOfRows=50&sortOrder=author_sort_asc&sortOrder2=title_sort_asc&onlyFullText=false&sf=all">PhD Thesis</a> 
  <br>  
  <a href="https://scholar.google.com/citations?user=Y5_hmZcAAAAJ&hl=en">Google Scholar Profile</a> 
  <br>  
  <a href="https://se.linkedin.com/in/richard-fridstrom">LinkedIn Profile</a>
  <br>
  
theme: jekyll-theme-minimal
