title: Richard Fridström # your name (or website title) here
logo: "jagKTH (2).jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  > Physics (PhD in Fusion Plasma Physics) 
  <br>
  > Mathematical modelling and signal analysis (MATLAB) 
  <br>
  > Programming  (Python, C#, Java)
  <br><br>
  <a href="https://scholar.google.com/citations?user=Y5_hmZcAAAAJ&hl=en">Google Scholar Profile</a> 
  <br>  
  <a href="https://se.linkedin.com/in/richard-fridstrom">LinkedIn Profile</a>
  <br>
  
  

theme: jekyll-theme-minimal
